apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: gcr.io/heptio-images/ks-guestbook-demo:^0.1
  name: flask-sample
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-flask
    repoURL: https://github.com/sergklm98/argocd-iu
    targetRevision: HEAD
    helm:
      releaseName: flask-sample
      parameters:
        - name: containerPort
          value: '5000'
        - name: image.repository
          value: docker.io/sergklm1/flask-sample
        - name: image.tag
          value: latest
        - name: image.pullPolicy
          value: Always
  syncPolicy:
    automated:
      prune: true