name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker images
      run: |
        docker build -t sergklm1/flask-sample:latest ./app
        docker login -u sergklm1 -p ${{ secrets.DOCKER_PASSWORD }}
        docker push sergklm1/flask-sample:latest
